
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or master, depending on your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is often needed for actions that push to the repo
      pages: write    # Needed for deploying to GitHub Pages
      id-token: write # Needed for OIDC, which gh-pages action might use

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a recent LTS version

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          # run_install: true # Removed to explicitly run install with --frozen-lockfile

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Assuming 'dist' is your build output directory
          # cname: example.com # Uncomment and set if you have a custom domain
